// Generate sux/FUNCTIONS.md from the function source files. Zero deps — parses
// each fns/<name>.ts for its tool `name` + `description`, infers category and
// status, and emits a grouped reference table. Run: `npm run docs`.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { byImportance } from "./importance.mjs";

const FNS = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "fns");

// Category → ordered member tool names. Anything unlisted falls into "other".
const CATEGORIES = [
	["Net / transport", ["proxy", "scrape", "geo_fetch", "redirects", "robots", "crawl"]],
	["Extract / parse", ["extract", "readability", "tables", "metadata", "feed", "sitemap", "contacts", "select", "grep", "subtitles"]],
	["Convert", ["markdown", "html", "csv", "json", "xml", "yaml", "image_convert", "pdf", "fillable"]],
	["Compress / encode / data", ["compress", "encode", "hash", "archive"]],
	["Token optimization", ["pack", "declutter"]],
	["Text / AI", ["summarize", "translate", "classify", "ocr", "entities", "redact"]],
	["Batching / composition", ["batch", "batch_fetch", "pipe"]],
	["Storage (KV)", ["kv_get", "kv_put", "kv_list", "kv_delete", "store"]],
	["Feedback / meta", ["issue"]],
	["Query / APIs", ["search", "web_search", "shop", "wayback"]],
];

const files = readdirSync(FNS).filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && f !== "index.ts" && !f.startsWith("_"));

// Functions that need infra not yet wired (Browser Rendering / PDF-WASM /
// image transcode). They ship as honest fail() stubs. Explicit list beats
// fragile keyword-sniffing (which mis-flagged compress/office_to_pdf).
const PLANNED = new Set(["html_to_pdf", "pdf_to_text", "pdf_to_images", "office_to_pdf"]);
const dir = readdirSync(FNS);

const byName = new Map();
for (const f of files) {
	const src = readFileSync(join(FNS, f), "utf8");
	const name = src.match(/name:\s*"([^"]+)"/)?.[1] ?? f.replace(/\.ts$/, "");
	const desc = (src.match(/description:\s*\n?\s*"((?:[^"\\]|\\.)*)"/)?.[1] ?? "").replace(/\\"/g, '"');
	const stub = PLANNED.has(name);
	const tested = dir.includes(f.replace(/\.ts$/, ".test.ts"));
	byName.set(name, { name, desc, stub, tested });
}

// Fail loudly when CATEGORIES references a function that no longer exists —
// otherwise renames silently push functions into "Other" (doc drift).
const missing = CATEGORIES.flatMap(([, names]) => names).filter((n) => !byName.has(n));
if (missing.length) {
	console.error(`gen-docs: CATEGORIES references unknown function(s): ${missing.join(", ")}`);
	process.exit(1);
}

const one = (s) => {
	const t = s.split(/\.\s/)[0].trim();
	return (t.length > 100 ? `${t.slice(0, 100)}…` : t).replace(/\|/g, "\\|");
};

let total = 0;
let working = 0;
let tested = 0;
const seen = new Set();
let body = "";
for (const [cat, names] of CATEGORIES) {
	const rows = [];
	for (const n of [...names].sort(byImportance)) {
		const fn = byName.get(n);
		if (!fn) continue;
		seen.add(n);
		total++;
		if (!fn.stub) working++;
		if (fn.tested) tested++;
		const status = fn.stub ? "🟡 planned" : "✅";
		rows.push(`| \`${fn.name}\` | ${status} | ${fn.tested ? "✓" : "—"} | ${one(fn.desc)} |`);
	}
	if (!rows.length) continue;
	body += `\n### ${cat} (${rows.length})\n\n| function | status | test | summary |\n|---|---|---|---|\n${rows.join("\n")}\n`;
}
// Anything not categorized.
const other = [...byName.keys()].filter((n) => !seen.has(n)).sort();
if (other.length) {
	body += `\n### Other (${other.length})\n\n| function | status | test | summary |\n|---|---|---|---|\n`;
	for (const n of other) {
		const fn = byName.get(n);
		total++;
		if (!fn.stub) working++;
		if (fn.tested) tested++;
		body += `| \`${fn.name}\` | ${fn.stub ? "🟡 planned" : "✅"} | ${fn.tested ? "✓" : "—"} | ${one(fn.desc)} |\n`;
	}
}

const md = `# sux — function reference

> Auto-generated by \`npm run docs\` from \`sux/src/fns/*.ts\`. Do not edit by hand.

**${total} functions** · ${working} working · ${total - working} planned · ${tested} with tests.
Each function is one \`Fn\` file, projected into the MCP \`tools/list\` by \`src/registry.ts\`.
Status: ✅ working · 🟡 planned (needs a binding/WASM not yet wired).
${body}
---

_Legend_: every function returns MCP text content; binary I/O is base64 inside JSON.
Cacheable functions are memoized in KV by a hash of their arguments.
`;

writeFileSync(join(FNS, "..", "..", "FUNCTIONS.md"), md);
console.log(`Wrote FUNCTIONS.md — ${total} functions (${working} working, ${tested} tested).`);
