#!/usr/bin/env node
// Regenerates the code-derived knowledge artifacts so the living wiki never
// drifts from source. Two audiences, two shapes:
//   human  ->  docs/wiki/MOCs/Functions-MOC.md
//              docs/wiki/MOCs/Status-Dashboard.md
//   Claude ->  llms.txt  (terse, dense, whole-vault index at the repo root)
//
// Markdown notes preserve everything above their GENERATED marker; below it is
// overwritten. llms.txt is fully generated. Run after `npm run docs`.
// See docs/wiki/Meta/wiki-protocol.md and wiki-conventions.md.

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, relative, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MARKER = "<!-- GENERATED by scripts/gen-wiki.mjs — do not edit below this line -->";
const check = process.argv.includes("--check");

const rel = (p) => relative(ROOT, p).split("\\").join("/");
// No date stamps in generated output: the commit hook regenerates on every
// commit, so output must be content-deterministic (a date would churn every file).

// ---- tiny frontmatter reader (no deps) -------------------------------------
function parseNote(text) {
  if (!text.startsWith("---\n")) return { fm: null, body: text };
  const end = text.indexOf("\n---", 4);
  if (end === -1) return { fm: null, body: text };
  const fmText = text.slice(4, end);
  const body = text.slice(end + 4);
  const fm = {};
  for (const line of fmText.split("\n")) {
    const m = line.match(/^([A-Za-z_]+):\s*(.*)$/);
    if (m) fm[m[1]] = m[2].trim();
  }
  return { fm, body };
}
const unquote = (v = "") => v.replace(/^["']|["']$/g, "").trim();

// terse one-liner for a note: explicit `summary:` frontmatter, else the first
// real prose sentence of the body (skipping H1, Source, callouts, blanks).
function summaryOf(fm, body) {
  if (fm && fm.summary) return unquote(fm.summary);
  for (let line of body.split("\n")) {
    line = line.trim();
    if (!line || line.startsWith("#") || line.startsWith(">") || /^\*?\*?Source/.test(line)) continue;
    const plain = line.replace(/[*`]/g, ""); // strip emphasis/code marks, keep underscores in identifiers
    const dot = plain.indexOf(". ");
    return (dot > 0 ? plain.slice(0, dot + 1) : plain).trim();
  }
  return "";
}

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const s = statSync(p);
    if (s.isDirectory()) walk(p, out);
    else if (name.endsWith(".md")) out.push(p);
  }
  return out;
}

// one scan of every frontmattered note under docs/ (+ Home.md) — the shared
// data for the dashboard and the llms index.
function scanNotes() {
  const files = walk(join(ROOT, "docs"));
  const home = join(ROOT, "Home.md");
  if (existsSync(home)) files.push(home);
  const notes = [];
  for (const f of files) {
    const { fm, body } = parseNote(readFileSync(f, "utf8"));
    if (!fm || !fm.status) continue;
    notes.push({
      title: unquote(fm.title) || basename(f, ".md"),
      status: unquote(fm.status),
      cluster: unquote(fm.cluster) || "—",
      type: (unquote(fm.type) || "").toLowerCase(),
      link: basename(f, ".md"),
      path: rel(f),
      summary: summaryOf(fm, body),
    });
  }
  return notes;
}

// ---- write helper: preserve header above MARKER ----------------------------
function emit(path, header, generated) {
  const tail = `${MARKER}\n<!-- regenerate: npm run wiki -->\n\n${generated}\n`;
  const prev = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (prev.includes(MARKER)) {
    const merged = `${prev.slice(0, prev.indexOf(MARKER))}${tail}`;
    if (check) return prev === merged;
    if (prev !== merged) writeFileSync(path, merged);
    return true;
  }
  const next = `${header}\n${tail}`;
  if (check) return prev === next;
  writeFileSync(path, next);
  return true;
}

function emitRaw(path, content) {
  const prev = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (check) return prev === content;
  if (prev !== content) writeFileSync(path, content);
  return true;
}

// ---- parse the function catalog from sux/FUNCTIONS.md -----------------------
function functionCatalog() {
  const src = readFileSync(join(ROOT, "sux/FUNCTIONS.md"), "utf8");
  const total = (src.match(/\*\*(\d+) functions\*\*/) || [])[1] || "?";
  const marks = [];
  const re = /^### (.+?) \((\d+)\)\s*$/gm;
  let m;
  while ((m = re.exec(src))) marks.push({ name: m[1], count: m[2], at: m.index });
  const sections = marks.map((mk, i) => {
    const block = src.slice(mk.at, i + 1 < marks.length ? marks[i + 1].at : src.length);
    const fns = [...block.matchAll(/^\| `([^`]+)` \| (\S+) \| (\S+) \| (.*?) \|$/gm)].map((r) => ({
      name: r[1], status: r[2], summary: r[4],
    }));
    return { name: mk.name, count: mk.count, fns };
  });
  return { total, sections };
}

// ---- 1. Functions MOC (human) ----------------------------------------------
function functionsMoc(cat) {
  const header = `---
title: Functions
status: shipped
cluster: meta
type: moc
tags: [sux, meta, functions]
---

# Functions MOC

The **${cat.total} functions** that make up the universal \`/mcp\` surface, grouped by
category. Generated from [\`sux/FUNCTIONS.md\`](../../../sux/FUNCTIONS.md) (itself
generated from \`sux/src/fns/*.ts\`) — see [[wiki-protocol]]. The per-fn
\`description\` shown in \`tools/list\` is the canonical doc; this is the map.

How a call flows through these: [[fn-registry]] → [[content-addressed-cache]] →
[[fetch-ladder]]. The stateless query plane is framed as ten front-door verbs in
[[sux-verbs]]; the parked one-verb-per-domain retrieval redesign lives in
[[Parked-Retrieval-MOC]].`;

  let body = `_Generated by \`npm run wiki\` · ${cat.total} functions · ${cat.sections.length} categories._\n`;
  for (const s of cat.sections) {
    body += `\n## ${s.name} (${s.count})\n\n`;
    for (const f of s.fns) body += `- \`${f.name}\` ${f.status} — ${f.summary}\n`;
  }
  return emit(join(ROOT, "docs/wiki/MOCs/Functions-MOC.md"), header, body);
}

// ---- 2. Status dashboard (human) -------------------------------------------
const STATUS_ORDER = ["shipped", "designed", "draft", "parked", "meta", "reference"];
const STATUS_BLURB = {
  shipped: "Built and running in production.",
  designed: "Design-locked, on the active build path, not yet built.",
  draft: "Proposed, not yet design-locked.",
  parked: "Explored to high polish, **not on the build path** (superseded by the [[SUX]] pivot).",
  meta: "Program-level coherence, strategy, and history.",
  reference: "Stable reference material.",
};
const SKIP_DASH = new Set(["moc", "dashboard", "reference", "concept"]);

function statusDashboard(notes) {
  const rows = notes.filter((n) => !SKIP_DASH.has(n.type));
  const counts = {};
  for (const r of rows) counts[r.status] = (counts[r.status] || 0) + 1;

  const header = `---
title: Status Dashboard
status: reference
cluster: meta
type: dashboard
tags: [sux, meta, dashboard]
---

# Status Dashboard

Every doc in the vault by lifecycle status, generated from \`status:\` frontmatter
(see [[wiki-conventions]]). When reality moves, flip a note's \`status:\` and run
\`npm run wiki\`. This is the one signal that keeps *shipped* from blurring into
*designed* into *parked*.`;

  let body = `_Generated by \`npm run wiki\` · ${rows.length} docs._\n\n`;
  body += "| status | count |\n|---|---|\n";
  for (const s of STATUS_ORDER) if (counts[s]) body += `| **${s}** | ${counts[s]} |\n`;
  for (const s of STATUS_ORDER) {
    const group = rows.filter((r) => r.status === s)
      .sort((a, b) => a.cluster.localeCompare(b.cluster) || a.title.localeCompare(b.title));
    if (!group.length) continue;
    body += `\n## ${s}\n\n${STATUS_BLURB[s] || ""}\n\n| doc | cluster |\n|---|---|\n`;
    for (const r of group) body += `| [[${r.link}\\|${r.title}]] | ${r.cluster} |\n`;
  }
  return emit(join(ROOT, "docs/wiki/MOCs/Status-Dashboard.md"), header, body);
}

// ---- 3. llms.txt (terse, Claude-optimized whole-vault index) ---------------
const CLUSTER_ORDER = ["namespaces", "knowledge", "infrastructure", "operations", "algebra", "retrieval", "meta"];

function llmsIndex(notes, cat) {
  const line = (n) => `- [[${n.link}]] (${n.status}) — ${n.summary}`;
  const docs = notes.filter((n) => n.type !== "concept" && n.type !== "moc" && n.type !== "dashboard");
  const concepts = notes.filter((n) => n.type === "concept");

  let out = `# sux — machine index (llms.txt)
# Generated by scripts/gen-wiki.mjs — do not edit by hand; run \`npm run wiki\`.
# Terse Claude-optimized companion to the human wiki (start: Home.md).
# ${notes.length} notes · ${cat.total} functions. Legend: shipped|designed|draft|parked|meta|reference.
# The SUX pivot made the knowledge-store the core and PARKED the web-retrieval/algebra program.

## Docs by cluster
`;
  for (const c of CLUSTER_ORDER) {
    const group = docs.filter((n) => n.cluster === c)
      .sort((a, b) => STATUS_ORDER.indexOf(a.status) - STATUS_ORDER.indexOf(b.status) || a.title.localeCompare(b.title));
    if (!group.length) continue;
    out += `\n### ${c}\n`;
    for (const n of group) out += `${line(n)}\n`;
  }

  out += `\n## Concept graph\n`;
  for (const n of concepts.sort((a, b) => a.link.localeCompare(b.link))) out += `${line(n)}\n`;

  out += `\n## Functions (${cat.total}, universal /mcp surface)\n`;
  for (const s of cat.sections) out += `- ${s.name}: ${s.fns.map((f) => f.name).join(", ")}\n`;

  return emitRaw(join(ROOT, "llms.txt"), out);
}

// ---- run -------------------------------------------------------------------
const notes = scanNotes();
const cat = functionCatalog();
const ok = [functionsMoc(cat), statusDashboard(notes), llmsIndex(notes, cat)].every(Boolean);

if (check) {
  if (!ok) {
    console.error("knowledge artifacts are stale — run `npm run wiki` and commit.");
    process.exit(1);
  }
  console.log("wiki + llms.txt in sync.");
} else {
  console.log(`Regenerated Functions-MOC.md, Status-Dashboard.md, llms.txt (${notes.length} notes, ${cat.total} fns)`);
}
