// Vault graph-health report (#1208, W4 of #1202): orphan notes, dead wikilinks, a stale-date
// distribution, and per-folder counts — the measurement pass the big prune/connect effort
// (post tree-research) steers by. Pure read over scanVault's index; the only write is the one
// regenerable Meta/Graph-Health.md summary (same "read-only report, one regenerable note"
// contract as _grafana_hook.ts's Alerts note / _document_radar.ts's per-document notes).
import { type Fn, ok, failWith, type RtEnv } from "../registry";
import { oj, errMsg } from "./_util";
import { linkResolvesTo, noteBasename } from "../vault-graph";
import { scanVault, type VaultRecord } from "../vault-mcp";
import { obsidian, vaultCfg } from "./obsidian";

const REPORT_PATH = "Meta/Graph-Health.md";
const SCAN_CAP = 2000;

const STALE_BUCKETS = ["<30d", "30-90d", "90-365d", ">365d", "unknown"] as const;
type StaleBucket = (typeof STALE_BUCKETS)[number];

/** First plausible "last touched" frontmatter signal, in the order this repo's writers
 *  actually stamp notes (ingest.ts's `created`, _consolidate.ts's `last_verified`, plain
 *  `updated`/`modified`/`date`) — the first one that parses wins, so a note carrying several
 *  isn't double-counted. */
function dateSignal(fm: Record<string, unknown>): Date | null {
	for (const key of ["updated", "modified", "last_verified", "created", "date"]) {
		const v = fm[key];
		if (typeof v !== "string" || !v.trim()) continue;
		const d = new Date(v);
		if (!Number.isNaN(d.getTime())) return d;
	}
	return null;
}

function staleBucket(fm: Record<string, unknown>, now: Date): StaleBucket {
	const d = dateSignal(fm);
	if (!d) return "unknown";
	const ageDays = (now.getTime() - d.getTime()) / 86_400_000;
	if (ageDays < 30) return "<30d";
	if (ageDays < 90) return "30-90d";
	if (ageDays < 365) return "90-365d";
	return ">365d";
}

/** A note's folder = everything before its last path segment, or "(root)" for a top-level
 *  note — matches how portal.ts/vault-mcp.ts already treat `path` as slash-separated. */
function noteFolder(path: string): string {
	const i = path.lastIndexOf("/");
	return i === -1 ? "(root)" : path.slice(0, i);
}

export type DeadLink = { path: string; link: string };
export type GraphHealth = {
	total: number;
	orphans: string[];
	orphan_count: number;
	dead_links: DeadLink[];
	dead_link_count: number;
	stale_distribution: Record<StaleBucket, number>;
	folder_counts: Record<string, number>;
};

/** Pure metric computation over an already-scanned vault index — no I/O, so it's directly
 *  unit-testable against hand-built VaultRecord[] fixtures. `now` is injectable for
 *  deterministic staleness-bucket tests. */
export function computeGraphHealth(records: VaultRecord[], now: Date = new Date()): GraphHealth {
	const orphans: string[] = [];
	const dead_links: DeadLink[] = [];
	const stale_distribution: Record<StaleBucket, number> = { "<30d": 0, "30-90d": 0, "90-365d": 0, ">365d": 0, unknown: 0 };
	const folder_counts: Record<string, number> = {};

	const hasInbound = (path: string): boolean => records.some((r) => r.path !== path && r.links.some((l) => linkResolvesTo(l, path)));

	for (const r of records) {
		const outbound = r.links.length > 0;
		if (!outbound && !hasInbound(r.path)) orphans.push(r.path);

		for (const link of r.links) {
			if (!records.some((other) => linkResolvesTo(link, other.path))) dead_links.push({ path: r.path, link });
		}

		stale_distribution[staleBucket(r.fm, now)]++;

		const folder = noteFolder(r.path);
		folder_counts[folder] = (folder_counts[folder] ?? 0) + 1;
	}

	return {
		total: records.length,
		orphans,
		orphan_count: orphans.length,
		dead_links,
		dead_link_count: dead_links.length,
		stale_distribution,
		folder_counts,
	};
}

function renderReport(h: GraphHealth, generatedAt: string): string {
	const lines: string[] = [];
	lines.push("---");
	lines.push("type: graph_health");
	lines.push("tags: [graph-health, meta]");
	lines.push(`generated: ${generatedAt}`);
	lines.push("---");
	lines.push("");
	lines.push("# Vault Graph Health");
	lines.push("");
	lines.push(`Auto-regenerated by \`graph_health\`. ${h.total} note(s) scanned.`);
	lines.push("");
	lines.push(`## Orphans (${h.orphan_count}) — no inbound or outbound links`);
	lines.push(h.orphans.length ? h.orphans.map((p) => `- \`${p}\``).join("\n") : "_none_");
	lines.push("");
	lines.push(`## Dead links (${h.dead_link_count}) — [[wikilink]] target with no matching note`);
	lines.push(h.dead_links.length ? h.dead_links.map((d) => `- \`${d.path}\` → \`[[${d.link}]]\``).join("\n") : "_none_");
	lines.push("");
	lines.push("## Staleness distribution");
	lines.push("| bucket | notes |");
	lines.push("| --- | --- |");
	for (const b of STALE_BUCKETS) lines.push(`| ${b} | ${h.stale_distribution[b]} |`);
	lines.push("");
	lines.push("## Per-folder counts");
	lines.push("| folder | notes |");
	lines.push("| --- | --- |");
	for (const [folder, count] of Object.entries(h.folder_counts).sort((a, b) => b[1] - a[1])) lines.push(`| ${folder} | ${count} |`);
	lines.push("");
	return lines.join("\n");
}

export const graph_health: Fn = {
	name: "graph_health",
	description:
		"Read-only vault graph-health report (#1208): orphan notes (zero inbound AND zero outbound links), dead [[wikilinks]] (a link target with no matching note), a stale-date distribution (<30d/30-90d/90-365d/>365d/unknown, keyed off frontmatter updated/modified/last_verified/created/date), and per-folder note counts. Scans the vault via the same cached index vault_backlinks/vault_query use, then writes a regenerable Meta/Graph-Health.md summary and returns the same metrics as JSON. The instrumentation a prune/connect pass steers by — measurement, never a mutation of note content.",
	inputSchema: { type: "object", additionalProperties: false, required: [], properties: {} },
	cacheable: false,
	annotations: { readOnlyHint: true, openWorldHint: false },
	run: async (env: RtEnv) => {
		const cfg = vaultCfg(env);
		if ("error" in cfg) return failWith("not_configured", cfg.error);

		let records: VaultRecord[];
		try {
			({ records } = await scanVault(env, undefined, SCAN_CAP));
		} catch (e) {
			return failWith("upstream_error", `graph_health: vault scan failed: ${errMsg(e)}`);
		}

		// Exclude the report's own generated note — its body documents other notes' dead
		// links as literal `[[wikilink]]` example text, which the regex-based scan would
		// otherwise re-parse as outgoing links from the report itself, self-inflating the
		// count on every subsequent run (#1261).
		const health = computeGraphHealth(records.filter((r) => r.path !== REPORT_PATH));
		const generatedAt = new Date().toISOString();
		const w = await obsidian.run(env, { action: "write", path: REPORT_PATH, content: renderReport(health, generatedAt), backend: "git" });
		const note_written = !w.isError;

		return ok(oj({ ...health, note_path: REPORT_PATH, note_written, generated_at: generatedAt }));
	},
};
