// Function manifest — GENERATED by scripts/gen-index.mjs (npm run gen:index).
// Ordered by scripts/importance.mjs so the MCP tools/list surfaces the most
// important tools first. Add a function = create fns/<name>.ts (export const
// <name>: Fn) and re-run the generator.

import type { Fn } from "../registry";
import { search } from "./search";
import { scrape } from "./scrape";
import { proxyFn } from "./proxy";
import { extract } from "./extract";
import { readability } from "./readability";
import { summarize } from "./summarize";
import { grep } from "./grep";
import { select } from "./select";
import { pack } from "./pack";
import { compress } from "./compress";
import { batch } from "./batch";
import { batch_fetch } from "./batch_fetch";
import { metadata } from "./metadata";
import { tables } from "./tables";
import { archive } from "./archive";
import { encode } from "./encode";
import { hash } from "./hash";
import { feed } from "./feed";
import { sitemap } from "./sitemap";
import { contacts } from "./contacts";
import { entities } from "./entities";
import { redact } from "./redact";
import { translate } from "./translate";
import { classify } from "./classify";
import { ocr } from "./ocr";
import { pubmed } from "./pubmed";
import { clinical_trials } from "./clinical_trials";
import { youtube } from "./youtube";
import { wayback } from "./wayback";
import { geo_fetch } from "./geo_fetch";
import { redirects } from "./redirects";
import { robots } from "./robots";
import { crawl } from "./crawl";
import { subtitles } from "./subtitles";
import { kv_get } from "./kv_get";
import { kv_put } from "./kv_put";
import { kv_list } from "./kv_list";
import { kv_delete } from "./kv_delete";
import { issue } from "./issue";
import { imageConvert } from "./image_convert";
import { ace } from "./ace";
import { alphavantage } from "./alphavantage";
import { amazon } from "./amazon";
import { arxiv } from "./arxiv";
import { bestbuy } from "./bestbuy";
import { coingecko } from "./coingecko";
import { costco } from "./costco";
import { crossref } from "./crossref";
import { csv } from "./csv";
import { declutter } from "./declutter";
import { ebay } from "./ebay";
import { etsy } from "./etsy";
import { facebook } from "./facebook";
import { fillable } from "./fillable";
import { find_similar } from "./find_similar";
import { fontcase } from "./fontcase";
import { guardian } from "./guardian";
import { homedepot } from "./homedepot";
import { html } from "./html";
import { json } from "./json";
import { kroger } from "./kroger";
import { linkedin } from "./linkedin";
import { lowes } from "./lowes";
import { markdown } from "./markdown";
import { nyt } from "./nyt";
import { obsidian } from "./obsidian";
import { openalex } from "./openalex";
import { pdf } from "./pdf";
import { people } from "./people";
import { pipe } from "./pipe";
import { places } from "./places";
import { render } from "./render";
import { semantic_scholar } from "./semantic_scholar";
import { shop } from "./shop";
import { stackexchange } from "./stackexchange";
import { store } from "./store";
import { tavily } from "./tavily";
import { tmdb } from "./tmdb";
import { walmart } from "./walmart";
import { webSearch } from "./web_search";
import { wolfram } from "./wolfram";
import { xml } from "./xml";
import { yaml } from "./yaml";

export const FUNCTIONS: Fn[] = [
	search,
	scrape,
	proxyFn,
	extract,
	readability,
	summarize,
	grep,
	select,
	pack,
	compress,
	batch,
	batch_fetch,
	metadata,
	tables,
	archive,
	encode,
	hash,
	feed,
	sitemap,
	contacts,
	entities,
	redact,
	translate,
	classify,
	ocr,
	pubmed,
	clinical_trials,
	youtube,
	wayback,
	geo_fetch,
	redirects,
	robots,
	crawl,
	subtitles,
	kv_get,
	kv_put,
	kv_list,
	kv_delete,
	issue,
	imageConvert,
	ace,
	alphavantage,
	amazon,
	arxiv,
	bestbuy,
	coingecko,
	costco,
	crossref,
	csv,
	declutter,
	ebay,
	etsy,
	facebook,
	fillable,
	find_similar,
	fontcase,
	guardian,
	homedepot,
	html,
	json,
	kroger,
	linkedin,
	lowes,
	markdown,
	nyt,
	obsidian,
	openalex,
	pdf,
	people,
	pipe,
	places,
	render,
	semantic_scholar,
	shop,
	stackexchange,
	store,
	tavily,
	tmdb,
	walmart,
	webSearch,
	wolfram,
	xml,
	yaml,
];
