// Function manifest — GENERATED by scripts/gen-index.mjs (npm run gen:index).
// Ordered by scripts/importance.mjs so the MCP tools/list surfaces the most
// important tools first. Add a function = create fns/<name>.ts (export const
// <name>: Fn) and re-run the generator.

import type { Fn } from "../registry";
import { search } from "./search";
import { fnEscape } from "./fn";
import { scrape } from "./scrape";
import { render } from "./render";
import { proxyFn } from "./proxy";
import { extract } from "./extract";
import { readability } from "./readability";
import { summarize } from "./summarize";
import { grep } from "./grep";
import { select } from "./select";
import { pack } from "./pack";
import { compress } from "./compress";
import { declutter } from "./declutter";
import { batch } from "./batch";
import { batch_fetch } from "./batch_fetch";
import { metadata } from "./metadata";
import { tables } from "./tables";
import { markdown } from "./markdown";
import { html } from "./html";
import { csv } from "./csv";
import { json } from "./json";
import { xml } from "./xml";
import { yaml } from "./yaml";
import { archive } from "./archive";
import { encode } from "./encode";
import { hash } from "./hash";
import { feed } from "./feed";
import { sitemap } from "./sitemap";
import { extract_contacts } from "./extract_contacts";
import { entities } from "./entities";
import { redact } from "./redact";
import { translate } from "./translate";
import { classify } from "./classify";
import { ocr } from "./ocr";
import { pubmed } from "./pubmed";
import { clinical_trials } from "./clinical_trials";
import { youtube } from "./youtube";
import { wayback } from "./wayback";
import { redirects } from "./redirects";
import { robots } from "./robots";
import { crawl } from "./crawl";
import { subtitles } from "./subtitles";
import { pdf } from "./pdf";
import { fillable } from "./fillable";
import { imageConvert } from "./image_convert";
import { webSearch } from "./web_search";
import { tavily } from "./tavily";
import { find_similar } from "./find_similar";
import { arxiv } from "./arxiv";
import { openalex } from "./openalex";
import { crossref } from "./crossref";
import { semantic_scholar } from "./semantic_scholar";
import { stackexchange } from "./stackexchange";
import { reddit } from "./reddit";
import { coingecko } from "./coingecko";
import { shop } from "./shop";
import { product_search } from "./product_search";
import { amazon } from "./amazon";
import { walmart } from "./walmart";
import { homedepot } from "./homedepot";
import { lowes } from "./lowes";
import { bestbuy } from "./bestbuy";
import { ebay } from "./ebay";
import { costco } from "./costco";
import { kroger } from "./kroger";
import { ace } from "./ace";
import { weekly_ad } from "./weekly_ad";
import { people } from "./people";
import { people_finder } from "./people_finder";
import { places } from "./places";
import { linkedin } from "./linkedin";
import { facebook } from "./facebook";
import { ingest } from "./ingest";
import { citation } from "./citation";
import { consolidate } from "./consolidate";
import { oracle } from "./oracle";
import { study } from "./study";
import { advise } from "./advise";
import { learn } from "./learn";
import { preferences } from "./preferences";
import { life_wiki } from "./life_wiki";
import { agenda } from "./agenda";
import { jmap } from "./jmap";
import { mail_triage } from "./mail_triage";
import { mail_sieve } from "./mail_sieve";
import { mail_sieve_backfill } from "./mail_sieve_backfill";
import { briefing } from "./briefing";
import { vault } from "./vault";
import { mail } from "./mail";
import { files } from "./files";
import { calendar } from "./calendar";
import { contact } from "./contact";
import { monarch } from "./monarch";
import { mychart } from "./mychart";
import { pipe } from "./pipe";
import { watch } from "./watch";
import { watch_pipeline } from "./watch_pipeline";
import { kv_get } from "./kv_get";
import { kv_put } from "./kv_put";
import { kv_list } from "./kv_list";
import { kv_delete } from "./kv_delete";
import { store } from "./store";
import { put } from "./put";
import { dropbox } from "./dropbox";
import { issue } from "./issue";
import { suggest } from "./suggest";
import { proposals } from "./proposals";
import { selftest } from "./selftest";
import { autonomy_status } from "./autonomy_status";
import { controld } from "./controld";
import { tailscale } from "./tailscale";
import { obsidian } from "./obsidian";
import { sux } from "./sux";
import { todoist } from "./todoist";
import { voice } from "./voice";
import { fontcase } from "./fontcase";
import { recall } from "./recall";
import { get } from "./get";
import { uw } from "./uw";
import { run } from "./run";

export const FUNCTIONS: Fn[] = [
	search,
	fnEscape,
	scrape,
	render,
	proxyFn,
	extract,
	readability,
	summarize,
	grep,
	select,
	pack,
	compress,
	declutter,
	batch,
	batch_fetch,
	metadata,
	tables,
	markdown,
	html,
	csv,
	json,
	xml,
	yaml,
	archive,
	encode,
	hash,
	feed,
	sitemap,
	extract_contacts,
	entities,
	redact,
	translate,
	classify,
	ocr,
	pubmed,
	clinical_trials,
	youtube,
	wayback,
	redirects,
	robots,
	crawl,
	subtitles,
	pdf,
	fillable,
	imageConvert,
	webSearch,
	tavily,
	find_similar,
	arxiv,
	openalex,
	crossref,
	semantic_scholar,
	stackexchange,
	reddit,
	coingecko,
	shop,
	product_search,
	amazon,
	walmart,
	homedepot,
	lowes,
	bestbuy,
	ebay,
	costco,
	kroger,
	ace,
	weekly_ad,
	people,
	people_finder,
	places,
	linkedin,
	facebook,
	ingest,
	citation,
	consolidate,
	oracle,
	study,
	advise,
	learn,
	preferences,
	life_wiki,
	agenda,
	jmap,
	mail_triage,
	mail_sieve,
	mail_sieve_backfill,
	briefing,
	vault,
	mail,
	files,
	calendar,
	contact,
	monarch,
	mychart,
	pipe,
	watch,
	watch_pipeline,
	kv_get,
	kv_put,
	kv_list,
	kv_delete,
	store,
	put,
	dropbox,
	issue,
	suggest,
	proposals,
	selftest,
	autonomy_status,
	controld,
	tailscale,
	obsidian,
	sux,
	todoist,
	voice,
	fontcase,
	recall,
	get,
	uw,
	run,
];
